### ISSUE TITLE
Manually run a maintenance task

### ISSUE THREAD

**Issue by avilaplana** [GerritForge/GHS#10]
**Scenario 1: Manually trigger task successfully**

_Precondition_: system is running and the following configuration is loaded:

```
projects:
    project1:
        command: "rm"
        parameters: "-fr"
    project2:
        command: "jgit gc"
        parameters: "--prune=now"
```

* When the admin makes a POST request to `/tasks/project1`
* Then the command `rm -fr` will be scheduled
* And a 202 response with a UUID for the task will be returned

*NOTE*:
* format of the response TBD
* information about the tasks will be added in the logs
* review the verb and response status

**Scenario 2: Manually trigger task fails (becuase the project doesn't exist)**

_Precondition_: system is running and the following configuration is loaded:

```
projects:
    project1:
        command: "rm"
        parameters: "-fr"
    project2:
        command: "jgit gc"
        parameters: "--prune=now"
```

* When the admin makes a POST request to `/tasks/projectX`
* Then a 404 response will be returned

*NOTES:* review the verb and response status
