### ISSUE TITLE
Load the task execution configuration

### ISSUE THREAD

**Issue by avilaplana** [GerritForge/GHS#8]
**Scenario 1: Config loading**

* Given a single YAML file `tasks.yaml` like the following:
```
projects:
    project1:
        command: "rm"
        parameters: "-fr"
    project2:
        command: "jgit gc"
        parameters: "--prune=now"
```
* When the system starts
* Then the configuration is loaded in memory

**Scenario 2: Config re-loading**

_Precondition_: the system is running

* Given a valid change in the configuration YAML file
* When the system re-starts
* Then the configuration is loaded in memory

**NOTE:** the system must be restarted to re-load the config

**Scenario 3: System doesn't start**

* Given an invalid YAML file
* When the system starts
* Then it will emit a log error
* And it will exit

**NOTE:**
* when restarting the system to apply a configuration, make sure there are no tasks running. A graceful stop period might have to be introduced (TBD).
